[versions]
app-barcodes-version-code = "25"
app-barcodes-version-name = "1.0.2"
app-cat-fact-version-code = "1"
app-cat-fact-version-name = "0.0.1"
app-cosmos-design-system-catalog-version-code = "6"
app-cosmos-design-system-catalog-version-name = "1.0.5"
app-finance-manager-version-code = "20"
app-finance-manager-version-name = "1.0.19"
app-make-apps-simple-version-code = "1"
app-make-apps-simple-version-name = "0.1.0"
library-cosmos-design-system-version-code = "6"
library-cosmos-design-system-version-name = "1.0.5"

android-compile-sdk = "36"
android-min-sdk = "29"
android-target-sdk = "36"

androidx-activity = "1.13.0"
androidx-lifecycle = "2.11.0-beta01"
compose = "1.11.0"
java = "11"
kotlin = "2.3.21"
kotlin-wrappers-browser = "2026.5.6"
kotlinx-coroutines = "1.11.0"
material3 = "1.11.0-alpha07"
plugin-android-application = "9.1.1"

[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
compose-components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "compose" }
compose-foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
compose-runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "org.jetbrains.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "org.jetbrains.compose.ui:ui-tooling-preview", version.ref = "compose" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-wrappers-browser = { module = "org.jetbrains.kotlin-wrappers:kotlin-browser", version.ref = "kotlin-wrappers-browser" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

[plugins]
plugin-android-application = { id = "com.android.application", version.ref = "plugin-android-application" }
plugin-compose = { id = "org.jetbrains.compose", version.ref = "compose" }
plugin-kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
plugin-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
plugin-kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
plugin-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "plugin-android-application" }
